name: tftpget2http image builder

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - Dockerfile
      - .github
      - .gitignore
      - LICENSE
      - Makefile
      - README.md

env:
  imageregistry: 'quay.io'
  imagenamespace: ${{ secrets.IMAGENAMESPACE || secrets.QUAY_USERNAME }}
  latesttag: latest

jobs:

  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets are set
        id: have-secrets
        if: "${{ env.imagenamespace != '' }}"
        run: echo "::set-output name=ok::true"
    outputs:
      have-secrets: ${{ steps.have-secrets.outputs.ok }}

  build-tftpget2http:
    name: Build tftpget2http image using buildah
    runs-on: ubuntu-latest
    needs: [check-secrets]
    if: needs.check-secrets.outputs.have-secrets == 'true'

    steps:
    - uses: actions/checkout@v2

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5

    - name: Set latest tag for non master branch
      if: "${{ steps.branch-name.outputs.current_branch != 'master' }}"
      run: |
        echo "latesttag=${{ steps.branch-name.outputs.current_branch }}-latest" >> $GITHUB_ENV

    - name: Buildah Action
      id: build-tftpget2http
      uses: redhat-actions/buildah-build@v2
      with:
        image: tftpget2http
        tags: ${{ env.latesttag }} ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - name: Push tftpget2http To ${{ env.imageregistry }}
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-tftpget2http.outputs.image }}
        tags: ${{ steps.build-tftpget2http.outputs.tags }}
        registry: ${{ env.imageregistry }}/${{ env.imagenamespace }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}